/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MoodMenuRouteImport } from './routes/mood-menu'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivateEventsRouteImport } from './routes/private-events'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as WhatShouldIOrderRouteImport } from './routes/what-should-i-order'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodMenuRoute = MoodMenuRouteImport.update({
  id: '/mood-menu',
  path: '/mood-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateEventsRoute = PrivateEventsRouteImport.update({
  id: '/private-events',
  path: '/private-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatShouldIOrderRoute = WhatShouldIOrderRouteImport.update({
  id: '/what-should-i-order',
  path: '/what-should-i-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/mood-menu': typeof MoodMenuRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/private-events': typeof PrivateEventsRoute
  '/reservations': typeof ReservationsRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/visit': typeof VisitRoute
  '/what-should-i-order': typeof WhatShouldIOrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/mood-menu': typeof MoodMenuRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/private-events': typeof PrivateEventsRoute
  '/reservations': typeof ReservationsRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/visit': typeof VisitRoute
  '/what-should-i-order': typeof WhatShouldIOrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/mood-menu': typeof MoodMenuRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/private-events': typeof PrivateEventsRoute
  '/reservations': typeof ReservationsRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/visit': typeof VisitRoute
  '/what-should-i-order': typeof WhatShouldIOrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/events'
    | '/experience'
    | '/faq'
    | '/gallery'
    | '/menu'
    | '/mood-menu'
    | '/offers'
    | '/privacy'
    | '/private-events'
    | '/reservations'
    | '/story'
    | '/terms'
    | '/visit'
    | '/what-should-i-order'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/events'
    | '/experience'
    | '/faq'
    | '/gallery'
    | '/menu'
    | '/mood-menu'
    | '/offers'
    | '/privacy'
    | '/private-events'
    | '/reservations'
    | '/story'
    | '/terms'
    | '/visit'
    | '/what-should-i-order'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/events'
    | '/experience'
    | '/faq'
    | '/gallery'
    | '/menu'
    | '/mood-menu'
    | '/offers'
    | '/privacy'
    | '/private-events'
    | '/reservations'
    | '/story'
    | '/terms'
    | '/visit'
    | '/what-should-i-order'
    | '/admin/login'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ExperienceRoute: typeof ExperienceRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  MoodMenuRoute: typeof MoodMenuRoute
  OffersRoute: typeof OffersRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateEventsRoute: typeof PrivateEventsRoute
  ReservationsRoute: typeof ReservationsRoute
  StoryRoute: typeof StoryRoute
  TermsRoute: typeof TermsRoute
  VisitRoute: typeof VisitRoute
  WhatShouldIOrderRoute: typeof WhatShouldIOrderRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-menu': {
      id: '/mood-menu'
      path: '/mood-menu'
      fullPath: '/mood-menu'
      preLoaderRoute: typeof MoodMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-events': {
      id: '/private-events'
      path: '/private-events'
      fullPath: '/private-events'
      preLoaderRoute: typeof PrivateEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-should-i-order': {
      id: '/what-should-i-order'
      path: '/what-should-i-order'
      fullPath: '/what-should-i-order'
      preLoaderRoute: typeof WhatShouldIOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ExperienceRoute: ExperienceRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  MoodMenuRoute: MoodMenuRoute,
  OffersRoute: OffersRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateEventsRoute: PrivateEventsRoute,
  ReservationsRoute: ReservationsRoute,
  StoryRoute: StoryRoute,
  TermsRoute: TermsRoute,
  VisitRoute: VisitRoute,
  WhatShouldIOrderRoute: WhatShouldIOrderRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
